services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    command: bash -c "bundle exec rails db:prepare && bundle exec rails server -b 0.0.0.0 tailwindcss:watch"
    depends_on:
      - tailwind

  tailwind:
    build: .
    volumes:
      - ./:/app
    command: rails tailwindcss:watch
    stdin_open: true